@startuml
title Embedding Parent Documents

start


  :tokens = num_tokens_from_string(document.page_content);

  if (tokens > max_tokens?) then
    :splitted_docs = parent_splitter.split_documents([document]);
    while (More splitted_docs?) is (yes)
      :Assign parent_id = uuid4();
      :metadata={file_id,\n                    parent_id,\n                    source};
    endwhile (no)
  else
    :Assign parent_id = uuid4();
    :metadata={file_id,\n                    parent_id,\n                    source};
  endif

  :parent_docs;


' 5. Persist to vector DB
:store_in_vector_db(parent_docs);

stop
@enduml
